-- Añadir metadatos a la tabla de usuarios
ALTER TABLE users
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_at TIMESTAMP NULL,
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- Añadir metadatos a la tabla de vehículos
ALTER TABLE vehicles
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_at TIMESTAMP NULL,
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

