CREATE USER dapa_app WITH PASSWORD 'secret';

GRANT CONNECT ON DATABASE dapa TO dapa_app;
GRANT USAGE ON SCHEMA public TO dapa_app;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO dapa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO dapa_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dapa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO dapa_app;

GRANT CREATE ON SCHEMA public TO dapa_app;
